version: '3.9'

services:
  backend:
    container_name: compose-back-container
    build: 
      context: backend
      dockerfile: Dockerfile
    image: compose-back-optimal-image
    networks:
      - backend
    ports:
      - 4000:3000
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    container_name: compose-front-container
    build: 
      context: frontend
      dockerfile: Dockerfile
    networks:
      - frontend
    image: compose-front-optimal-image
    ports:
      - 3005:80

  postgres:
    container_name: postgres
    image: postgres
    networks:
      - backend
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - .env

networks:
  frontend:
  backend:

volumes:
  postgres_data: